path: D:\IT\Computer Vision\Object Detection\pest_detection\pest_detection_training\data\dataset
 
train: images/train
val: images/val
test: images/test

nc: 3
names:
  0: bo to
  1: bo map
  2: bo thon